# Generated by Django 6.1 on 2026-09-01 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Delivery Rider", "Marketing Associate", "Operations Manager".', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('department', models.CharField(help_text='e.g. Riders, Marketing, Management, Customer Support.', max_length=100)),
                ('location', models.CharField(default='Nairobi', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('gig', 'Gig / per-delivery')], default='full_time', max_length=20)),
                ('description', models.TextField(help_text='What the role involves.')),
                ('requirements', models.TextField(blank=True, help_text='One requirement per line.')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to stop accepting applications without deleting the listing.')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, help_text="Cover note / why you're a fit.")),
                ('resume_link', models.URLField(blank=True, help_text='Link to CV/portfolio (Google Drive, LinkedIn, etc.)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.joblisting')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
