# Generated by Django 5.2.17 on 2026-09-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional banner image shown at the top of the job listing.', null=True, upload_to='careers/'),
        ),
    ]
