# Generated by Django 6.1 on 2026-08-29 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Home', help_text='e.g. Home, Office', max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Used for M-Pesa STK push, e.g. 2547XXXXXXXX', max_length=20)),
                ('building_name', models.CharField(max_length=150)),
                ('apartment_number', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('area', models.CharField(help_text='Neighbourhood / estate', max_length=150)),
                ('city', models.CharField(default='Nairobi', max_length=100)),
                ('delivery_notes', models.TextField(blank=True, help_text='Gate code, landmark, preferred drop-off instructions, etc.')),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'delivery addresses',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=8)),
                ('volume_ml', models.PositiveIntegerField(blank=True, help_text='e.g. 500 for a 500ml bottle', null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_alcoholic', models.BooleanField(default=False, help_text='Alcoholic drinks may be restricted from online sale/delivery.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
