# Generated by Django 6.1 on 2026-08-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kilimani, Westlands', max_length=150, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, help_text='Fee in KES', max_digits=8)),
                ('estimated_minutes', models.PositiveIntegerField(default=45, help_text='Typical delivery time for this zone, in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to stop deliveries to this zone.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
