# Generated by Django 6.1 on 2026-08-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_deliveryzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Captured from the browser/device GPS, if allowed.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Captured from the browser/device GPS, if allowed.', max_digits=9, null=True),
        ),
    ]
