# Generated by Django 6.1 on 2026-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_deliveryaddress_latitude_deliveryaddress_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Just a label for you, e.g. "Festive season".', max_length=100)),
                ('background_image', models.ImageField(blank=True, help_text='Sitewide ambient background, shown dimmed behind the glass UI.', null=True, upload_to='site/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='hero_description',
            field=models.CharField(blank=True, help_text='Short hero copy. Defaults to the product description if left blank.', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_headline',
            field=models.CharField(blank=True, help_text='Big hero headline. Defaults to the product name if left blank.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Short badge text for the hero slide, e.g. "20% off today". Defaults to "Featured".', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this product in the homepage hero slider.'),
        ),
    ]
