# Generated by Django 6.1 on 2026-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings_product_hero_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Just a label for you, e.g. "Festive season".', max_length=100)),
                ('image', models.ImageField(help_text='Sitewide ambient background, shown dimmed behind the glass UI.', upload_to='site/backgrounds/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one background is shown at a time — selecting this one deselects any other.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'background image',
                'verbose_name_plural': 'background images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
