# Generated by Django 6.1 on 2026-09-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_backgroundimage_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(help_text='Small label above the title, e.g. "First order", "This week", "Gifting".', max_length=60)),
                ('title', models.CharField(help_text='e.g. "20% off your first cart".', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('voucher_code', models.CharField(blank=True, help_text='e.g. WELCOME20. Leave blank to hide the code chip.', max_length=30)),
                ('tone', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('gold', 'Gold')], default='green', max_length=10)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Used when Media type is "Image". Stored on Cloudinary.', null=True, upload_to='promotions/images/')),
                ('video', models.FileField(blank=True, help_text='Used when Media type is "Video". MP4 recommended, keep it short — it autoplays muted and loops.', null=True, upload_to='promotions/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Alternative to uploading a file — a direct link to an already-hosted MP4. Used if no video file is uploaded.')),
                ('cta_label', models.CharField(default='Shop now', max_length=40)),
                ('cta_url', models.CharField(blank=True, help_text='Where the button links. Leave blank to link to the shop.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
