# Generated by Django 6.1 on 2026-09-05 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional "was" price shown struck through, e.g. 1500 when price is 1000 — auto-shows a "33% off" badge. Leave blank for no discount badge.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-unit price applied automatically once the quantity threshold is met.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_quantity_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Buying this many or more automatically switches to the wholesale unit price below.', null=True),
        ),
        migrations.CreateModel(
            name='BundleOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Shown on the product, e.g. "Buy 2 get 1 free Sprite 500ml".', max_length=150)),
                ('trigger_quantity', models.PositiveIntegerField(default=2)),
                ('reward_quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('reward_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_rewards', to='store.product')),
                ('trigger_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_triggers', to='store.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
