# Generated by Django 6.1 on 2026-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_compare_at_price_product_wholesale_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Just a label for you, e.g. "2026 rebrand".', max_length=100)),
                ('image', models.ImageField(help_text='Shown in the header. A wide/rectangular logo works best.', upload_to='site/logos/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one logo is shown at a time — selecting this one deselects any other.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'site logo',
                'verbose_name_plural': 'site logos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
