# Generated by Django 6.1 on 2026-09-01 06:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Shown on the wheel, e.g. "KES 200 cash voucher".', max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Cash voucher'), ('transport', 'Transport fee'), ('drinks', 'Drinks'), ('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('smart_tv', 'Smart TV'), ('try_again', 'Try again (no prize)')], max_length=20)),
                ('cash_value', models.DecimalField(blank=True, decimal_places=2, help_text='If set, this amount (KES) is credited to the wallet automatically on a win.', max_digits=10, null=True)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Relative odds — higher weight wins more often. Try_again prizes should carry most of the weight.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spin/prizes/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture — stored on Cloudinary.', null=True, upload_to='profiles/avatars/')),
                ('referral_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='The user whose referral code/link this person signed up through.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kind', models.CharField(choices=[('referral_bonus', 'Referral bonus'), ('referral_signup_bonus', 'Welcome bonus (referred)'), ('spin_win', 'Daily spin win'), ('adjustment', 'Manual adjustment')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spin_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wins', to='accounts.spinprize')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'spin_date')},
            },
        ),
    ]
