# Generated by Django 6.1 on 2026-09-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0007_product_compare_at_price_product_wholesale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspin',
            name='claim_address',
            field=models.ForeignKey(blank=True, help_text='Where to deliver a physical prize, captured when the user claims it.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='dailyspin',
            name='claim_status',
            field=models.CharField(choices=[('auto_credited', 'Auto-credited to wallet'), ('nothing_to_claim', 'No prize (try again)'), ('pending_claim', 'Awaiting claim'), ('claimed', 'Claimed — awaiting fulfilment'), ('fulfilled', 'Fulfilled')], default='nothing_to_claim', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyspin',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
