# Generated by Django 6.1 on 2026-09-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wallettransaction_kind_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral_bonus_released',
            field=models.BooleanField(default=False, help_text='Set automatically once this referral pays out — happens after the referred user completes their first paid order, not at signup, to discourage fake signups.'),
        ),
    ]
