# Generated by Django 6.1 on 2026-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_referral_bonus_released'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinWheelTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Just a label for you, e.g. "Festive wheel".', max_length=100)),
                ('image', models.ImageField(help_text='A square image works best — it fills the circular wheel face.', upload_to='site/spin-wheel/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one wheel image is shown at a time — selecting this one deselects any other.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'spin wheel image',
                'verbose_name_plural': 'spin wheel images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
