# Generated by Django 6.1 on 2026-09-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_assigned_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Shown to the customer — e.g. "You cancelled the M-Pesa prompt" or "Payment failed: insufficient funds".', max_length=255),
        ),
    ]
